[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_GOOGLE_CLIENT_ID = "779620201193-rtonlat3un9b31g20jikok7e0ub0dn6h.apps.googleusercontent.com"
  VITE_AWS_REGION = "us-east-1"
  VITE_S3_BUCKET_NAME = "ps-pics"